# This workflow runs composer and deploys the theme on a server

name: Deploy on package Server

on: [push, workflow_dispatch]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "greet"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: npm ci
            - run: npm run build
            - run: cat gutenberg-form.php | grep -m 1 -Pzo "(\/\*\*)(.|\n)*(\*\/)" >> version.txt
            - uses: thedoctor0/zip-release@0.7.5
              with:
                  type: 'zip'
                  filename: 'gutenberg-form.zip'
                  directory: '../'
                  path: 'gutenberg-form'
                  exclusions: '*.git* /*node_modules/* .editorconfig src/* .github/* src'
            - run: mv ../gutenberg-form.zip .
            - name: rsync deployments
              uses: burnett01/rsync-deployments@6.0.0
              with:
                  switches: -avzr --delete --include gutenberg-form.zip --include version.txt --include "readme.md" --include "changelog.md" --exclude "*"
                  path: /
                  remote_path: ${{ secrets.PACKAGE_PATH }}
                  remote_host: ${{ secrets.ALLINCL_SERVER }}
                  remote_user: ${{ secrets.ALLINCL_USER }}
                  remote_key: ${{ secrets.ALLINCL_KEY }}
